name: Pull request workflow

on:
  pull_request_target:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

#  push:
#    branches:
#      - main
permissions:
  contents: write

jobs:

  test_event_pull_request:
    name: Test event pull_request
    if: ${{ github.event.pull_request }}
    runs-on: ubuntu-latest
    steps:
      - name: step 1
        run: |
          echo "github.ref:"
          echo ${{ github.ref }} 
      - name: Extract PR details
        id: pr
        run: |
          PR_ID=pr-${{ github.event.pull_request.number }}
          PR_REF=refs/pull/${{ github.event.pull_request.number }}/merge
          echo "::set-output name=PR_ID::${PR_ID}"
          echo "::set-output name=PR_REF::${PR_REF}"


      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          #ref: ${{ steps.pr.outputs.PR_REF }}
          ref: refs/pull/${{ github.event.pull_request.number }}/merge

      - name: Checkout status
        run: |
          git remote -v
          git branch -a
          git branch

  test_event_pull_request_target:
    name: Test event pull_request_target
    if: ${{ github.event.pull_request_target }}
    runs-on: ubuntu-latest
    steps:
      - name: target step 1
        run: |
          echo "target github.ref:"
          echo ${{ github.ref }} 

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Checkout status
        run: |
          git remote -v
          git branch -a
          git branch
