name: Pull request workflow

on:
  pull_request:
    branches:
      - '*'

#  push:
#    branches:
#      - main
jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          node-version: 16
      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v3

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: Install node_modules
        run: yarn

      - name: Generate Site
        run: yarn generate

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2

  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{steps.deployment.outputs.page_url}}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: list
        run: |
          ls -al
          tree -L 2
          echo "${{steps.deployment.outputs.page_url}}"
          echo ${{steps.deployment.outputs.page_url}}
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
